const RouteName = {
  HOME_SCREEN: 'homescreen',
  HOME: 'home',
  PROFILE_SECTION: 'profile-section',
  BOTTOM_TAB: 'bottom-tab',
  WISHLIST_SCREEN: 'wishlist-screen',
  SHOPPING_BAG: 'shopping-bag',
  SUB_CATEGORY: 'subcategory',
  PRODUCT: 'product',
  PRODUCT_DETAIL: 'product-detail',
  TRENDING: 'trending',
  ADD_ADDRESS: 'add-address',
  ORDER_HISTORY: 'order-history',
  ORDER_DETAIL: 'order-detail',
  GIFT_CARD: 'gift-card',
  VOUCHER_DETAIL: 'voucher-detail',
  MY_ACCOUNT: 'my-account',
  ADDRESS_BOOK: 'address-book',
  AUTH_NAVIGATION: 'auth-navigation',
  LOGIN_SCREEN: 'login-screen',
  MOBILE_NUMBER_SCREEN: 'mobile-number-screen',
  OTP_SCREEN: 'otp-screen',
  SEARCH: 'search',
  PRODUCT_FILTER: 'product-filter',
  MODAL_NAVIGATOR: 'modal-navigator',
  SUCCESS_SCREEN: 'success-screen',
  REVIEW_SCREEN: 'review-screen',
  RATING_SCREEN: 'rating-screen',
  SUBCATEGORYLIST: 'subcategory-list',
  WALLET_SCREEN: 'wallet-screen',
  NEED_HELP: 'need-help',
  TOPUP_SCREEN: 'topup-screen',
  CHAT_NOW: 'chat-now',
};
export default RouteName;
